# Generated by Django 5.1.7 on 2025-03-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lloguer', '0002_reserva'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('automobil', 'fecha_inicio')},
        ),
    ]
